### ISSUE TITLE
Issues with editing text

### ISSUE THREAD

**Issue by danielwerg** [JuneDeveloper/Minecraft-Vanilla-Notebook#36]
- Pressing `backspace` at least once removes all new line (see video)
- `ctrl+backspace` doesn't work
- `delete` doesn't work

https://user-images.githubusercontent.com/35052399/202587033-c6094400-bafa-4e57-a9a0-1949b975efb6.mp4

Using version build from https://github.com/JuneDeveloper/Minecraft-Coordinate-Book/commit/7a28d13d81567655d0269f79cec326334694db73 commit

**Comment by JuneDeveloper** [comment]
`control+backspace` is a limitation of how i'm getting the text - but the delete button should be fixed now.
I am working on improving the enter key/multiple lines

**Comment by JuneDeveloper** [comment]
Enter key may be more complex than anticipated and i may temporarily remove the feature altogether (I have some plans for 2.0.0 which should help fix it, but for the alpha release it's really too ambitious)

**Comment by JuneDeveloper** [comment]
> Enter key may be more complex than anticipated and i may temporarily remove the feature altogether (I have some plans for 2.0.0 which should help fix it, but for the alpha release it's really too ambitious)

Also, want to add that the beta and full release will basically be an entire rewrite of the mod...
So the alpha release is just about getting it into a "doesn't need to be touched for a few weeks" state where i can focus on the next update.

The plan would be to, rather than use my method of storing data, use NBT, like a normal book, but that will take time (I haven't experimented with NBT data much in the past)
