### ISSUE TITLE
Crash when opening notebook - 1.19.2

### ISSUE THREAD

**Issue by Yuri-Almir-Pinto** [JuneDeveloper/Minecraft-Vanilla-Notebook#61]
https://crashy.net/05ebf684-de41-4a51-b101-5fd63dfc8aaf

When I try to open the notebook, the game crashes, and when I enter back in the the same world, my player model simply dissapears, as well as any block breaking particles.

**Comment by JuneDeveloper** [comment]
Are you using the correct version of the mod? Keep in mind you need the jar file for 1.19.2. This may be due to an incompatibility or config files not being correct (Try deleting the mod's configs, that may fix it).
Since I haven't touched much of minecraft's rendering code, the player model disappearing and block breaking particles are likely because of another mod.

**Comment by Yuri-Almir-Pinto** [comment]
> Are you using the correct version of the mod? Keep in mind you need the jar file for 1.19.2. This may be due to an incompatibility or config files not being correct (Try deleting the mod's configs, that may fix it). Since I haven't touched much of minecraft's rendering code, the player model disappearing and block breaking particles are likely because of another mod.

In theory, it was 2.2.0 for 1.19-1.19.2 (Downloaded from Prism Launcher).

Decided to download from modrinth directly, and delete the config file, and now it works normally.

Thanks for the help, don't know what happened, though... Didn't even touch the mod's config before this happened.
